# Generated by Django 2.2.1 on 2020-05-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='animation',
            field=models.BooleanField(default=False),
        ),
    ]
