# Generated by Django 2.2.1 on 2020-05-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_shows_animation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='animation',
            field=models.BooleanField(),
        ),
    ]
