# Generated by Django 2.2.1 on 2020-05-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_auto_20200525_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='animation',
            field=models.BooleanField(),
        ),
    ]
