# Generated by Django 2.2.1 on 2020-05-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_auto_20200525_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
