# Generated by Django 2.2.1 on 2020-05-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0007_auto_20200527_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shows',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
